In [1]:
# ================================
# Setup Cell: S&P 500 Universe + Metadata
# ================================

import os
from pathlib import Path
import pandas as pd
import requests
from bs4 import BeautifulSoup

# ---- Project Structure ----
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data"
UNIVERSE_DIR = DATA_DIR / "universe"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

UNIVERSE_DIR.mkdir(parents=True, exist_ok=True)
RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# ---- Universe Config ----
UNIVERSE_NAME = "sp500"

TICKER_FILE = UNIVERSE_DIR / f"{UNIVERSE_NAME}.csv"
UNIVERSE_METADATA_FILE = UNIVERSE_DIR / f"{UNIVERSE_NAME}_metadata.csv"

# ---- Always refresh universe metadata from Wikipedia ----
# This captures useful fields:
#   ticker, company, sector, sub_industry, headquarters, date_added, cik, founded
#
# Note:
#   This is current S&P 500 membership metadata, not historical membership.
#   For this project phase, we are using a current-constituent universe.

print("Fetching S&P 500 universe metadata...")

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")
table = soup.find("table", {"id": "constituents"})

sp500_raw = pd.read_html(str(table))[0]

sp500_metadata = sp500_raw.rename(columns={
    "Symbol": "ticker",
    "Security": "company",
    "GICS Sector": "sector",
    "GICS Sub-Industry": "sub_industry",
    "Headquarters Location": "headquarters",
    "Date added": "date_added",
    "CIK": "cik",
    "Founded": "founded",
}).copy()

sp500_metadata["ticker"] = (
    sp500_metadata["ticker"]
    .str.replace(".", "-", regex=False)  # BRK.B → BRK-B
    .str.upper()
    .str.strip()
)

sp500_metadata["date_added"] = pd.to_datetime(
    sp500_metadata["date_added"],
    errors="coerce",
)

# Keep clean metadata columns.
metadata_cols = [
    "ticker",
    "company",
    "sector",
    "sub_industry",
    "headquarters",
    "date_added",
    "cik",
    "founded",
]

sp500_metadata = sp500_metadata[
    [c for c in metadata_cols if c in sp500_metadata.columns]
].drop_duplicates(subset=["ticker"])

# ---- Save metadata and ticker-only universe ----
sp500_metadata.to_csv(UNIVERSE_METADATA_FILE, index=False)

tickers_df = sp500_metadata[["ticker"]].copy()
tickers_df.to_csv(TICKER_FILE, index=False)

# ---- Load tickers ----
tickers = (
    tickers_df["ticker"]
    .dropna()
    .str.upper()
    .str.strip()
    .unique()
    .tolist()
)

print(f"\nSaved metadata to: {UNIVERSE_METADATA_FILE}")
print(f"Saved ticker file to: {TICKER_FILE}")
print(f"Loaded {len(tickers)} tickers")
print("Sample:", tickers[:10])

sp500_metadata.head()

Fetching S&P 500 universe metadata...

Saved metadata to: /Users/neilyejjey/stock_signal_engine_v1/data/universe/sp500_metadata.csv
Saved ticker file to: /Users/neilyejjey/stock_signal_engine_v1/data/universe/sp500.csv
Loaded 503 tickers
Sample: ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A']

/var/folders/l3/hj4t10p12gs0m_nkjpjr9kqr0000gp/T/ipykernel_3408/2195897796.py:47: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  sp500_raw = pd.read_html(str(table))[0]

,ticker,company,sector,sub_industry,headquarters,date_added,cik,founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [2]:
tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APP',
 'APTV',
 'ACGL',
 'ADM',
 'ARES',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK-B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'XYZ',
 'BNY',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF-B',
 'BLDR',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CPT',
 'COF',
 'CAH',
 'CCL',
 'CARR',
 'CVNA',
 'CASY',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CIEN',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'COHR',
 'COIN',
 'CL',
 'CMCSA',
 'FIX',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CRH',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DDOG',
 'DVA',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'ETN',
 'EBAY',
 'ECHO',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'EME',
 'EMR',
 'ETR',
 'EOG',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FDXF',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FISV',
 'FLEX',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HPE',
 'HLT',
 'HD',
 'HONA',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'IBKR',
 'ICE',
 'IFF',
 'IP',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LITE',
 'LYB',
 'MTB',
 'MPC',
 'MAR',
 'MRSH',
 'MLM',
 'MRVL',
 'MAS',
 'MA',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PSKY',
 'PH',
 'PAYX',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'Q',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'HOOD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SNDK',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TTD',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VEEV',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VRT',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [3]:
# #in case modules not installed
# !pip install --upgrade pip setuptools wheel
# !pip install yfinance

In [4]:
# =========================================
# Download Price Data
# =========================================

import time
import yfinance as yf
import pandas as pd

# ---- Config ----
START_DATE = "2010-01-01"
END_DATE = "2026-01-01"   # exclusive in yfinance
SLEEP_SECONDS = 0.25      # tiny pause to be polite / reduce hiccups

PRICE_FILE = RAW_DIR / "prices.parquet"
FAILED_FILE = RAW_DIR / "failed_tickers.csv"

all_prices = []
failed_tickers = []

for i, ticker in enumerate(tickers, start=1):
    try:
        print(f"[{i}/{len(tickers)}] Downloading {ticker}...")

        df = yf.download(
            ticker,
            start=START_DATE,
            end=END_DATE,
            auto_adjust=False,   # keep raw OHLC + Adj Close
            actions=True,        # include dividends / splits when available
            progress=False,
            threads=False,
        )

        if df.empty:
            print(f"  -> No data returned for {ticker}")
            failed_tickers.append(ticker)
            continue

        # Flatten columns just in case
        df.columns = [
            col[0] if isinstance(col, tuple) else col
            for col in df.columns
        ]

        # Standardize column names
        df = df.reset_index().rename(columns={
            "Date": "date",
            "Open": "open",
            "High": "high",
            "Low": "low",
            "Close": "close",
            "Adj Close": "adj_close",
            "Volume": "volume",
            "Dividends": "dividends",
            "Stock Splits": "stock_splits",
        })

        # Add ticker
        df["ticker"] = ticker

        # Keep only the columns we care about
        expected_cols = [
            "date",
            "ticker",
            "open",
            "high",
            "low",
            "close",
            "adj_close",
            "volume",
            "dividends",
            "stock_splits",
        ]

        df = df[[col for col in expected_cols if col in df.columns]]

        # Ensure optional columns exist
        if "dividends" not in df.columns:
            df["dividends"] = 0.0

        if "stock_splits" not in df.columns:
            df["stock_splits"] = 0.0

        # Basic cleanup
        df["date"] = pd.to_datetime(df["date"])
        df = df.sort_values(["ticker", "date"]).drop_duplicates(
            subset=["ticker", "date"]
        )

        all_prices.append(df)

        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        print(f"  -> Failed for {ticker}: {e}")
        failed_tickers.append(ticker)

# ---- Combine all successful downloads ----
if not all_prices:
    raise ValueError("No price data was downloaded. Check tickers and internet/API availability.")

prices = pd.concat(all_prices, ignore_index=True)
prices = prices.sort_values(["ticker", "date"]).reset_index(drop=True)

# ---- Save outputs ----
prices.to_parquet(PRICE_FILE, index=False)

failed_df = pd.DataFrame({"ticker": failed_tickers})
failed_df.to_csv(FAILED_FILE, index=False)

print("\nDownload complete.")
print(f"Saved prices to: {PRICE_FILE}")
print(f"Saved failed tickers to: {FAILED_FILE}")
print(f"Price dataset shape: {prices.shape}")
print(f"Unique tickers downloaded: {prices['ticker'].nunique()}")
print(f"Failed tickers: {len(failed_tickers)}")

prices.head()

[1/503] Downloading MMM...
[2/503] Downloading AOS...
[3/503] Downloading ABT...
[4/503] Downloading ABBV...
[5/503] Downloading ACN...
[6/503] Downloading ADBE...
[7/503] Downloading AMD...
[8/503] Downloading AES...
[9/503] Downloading AFL...
[10/503] Downloading A...
[11/503] Downloading APD...
[12/503] Downloading ABNB...
[13/503] Downloading AKAM...
[14/503] Downloading ALB...
[15/503] Downloading ARE...
[16/503] Downloading ALGN...
[17/503] Downloading ALLE...
[18/503] Downloading LNT...
[19/503] Downloading ALL...
[20/503] Downloading GOOGL...
[21/503] Downloading GOOG...
[22/503] Downloading MO...
[23/503] Downloading AMZN...
[24/503] Downloading AMCR...
[25/503] Downloading AEE...
[26/503] Downloading AEP...
[27/503] Downloading AXP...
[28/503] Downloading AIG...
[29/503] Downloading AMT...
[30/503] Downloading AWK...
[31/503] Downloading AMP...
[32/503] Downloading AME...
[33/503] Downloading AMGN...
[34/503] Downloading APH...
[35/503] Downloading ADI...
[36/503] Downloading AON...
[37/503] Downloading APA...
[38/503] Downloading APO...
[39/503] Downloading AAPL...
[40/503] Downloading AMAT...
[41/503] Downloading APP...
[42/503] Downloading APTV...
[43/503] Downloading ACGL...
[44/503] Downloading ADM...
[45/503] Downloading ARES...
[46/503] Downloading ANET...
[47/503] Downloading AJG...
[48/503] Downloading AIZ...
[49/503] Downloading T...
[50/503] Downloading ATO...
[51/503] Downloading ADSK...
[52/503] Downloading ADP...
[53/503] Downloading AZO...
[54/503] Downloading AVB...
[55/503] Downloading AVY...
[56/503] Downloading AXON...
[57/503] Downloading BKR...
[58/503] Downloading BALL...
[59/503] Downloading BAC...
[60/503] Downloading BAX...
[61/503] Downloading BDX...
[62/503] Downloading BRK-B...
[63/503] Downloading BBY...
[64/503] Downloading TECH...
[65/503] Downloading BIIB...
[66/503] Downloading BLK...
[67/503] Downloading BX...
[68/503] Downloading XYZ...
[69/503] Downloading BNY...
[70/503] Downloading BA...
[71/503] Downloading BKNG...
[72/503] Downloading BSX...
[73/503] Downloading BMY...
[74/503] Downloading AVGO...
[75/503] Downloading BR...
[76/503] Downloading BRO...
[77/503] Downloading BF-B...
[78/503] Downloading BLDR...
[79/503] Downloading BG...
[80/503] Downloading BXP...
[81/503] Downloading CHRW...
[82/503] Downloading CDNS...
[83/503] Downloading CPT...
[84/503] Downloading COF...
[85/503] Downloading CAH...
[86/503] Downloading CCL...
[87/503] Downloading CARR...
[88/503] Downloading CVNA...
[89/503] Downloading CASY...
[90/503] Downloading CAT...
[91/503] Downloading CBOE...
[92/503] Downloading CBRE...
[93/503] Downloading CDW...
[94/503] Downloading COR...
[95/503] Downloading CNC...
[96/503] Downloading CNP...
[97/503] Downloading CF...
[98/503] Downloading CRL...
[99/503] Downloading SCHW...
[100/503] Downloading CHTR...
[101/503] Downloading CVX...
[102/503] Downloading CMG...
[103/503] Downloading CB...
[104/503] Downloading CHD...
[105/503] Downloading CIEN...
[106/503] Downloading CI...
[107/503] Downloading CINF...
[108/503] Downloading CTAS...
[109/503] Downloading CSCO...
[110/503] Downloading C...
[111/503] Downloading CFG...
[112/503] Downloading CLX...
[113/503] Downloading CME...
[114/503] Downloading CMS...
[115/503] Downloading KO...
[116/503] Downloading CTSH...
[117/503] Downloading COHR...
[118/503] Downloading COIN...
[119/503] Downloading CL...
[120/503] Downloading CMCSA...
[121/503] Downloading FIX...
[122/503] Downloading COP...
[123/503] Downloading ED...
[124/503] Downloading STZ...
[125/503] Downloading CEG...
[126/503] Downloading COO...
[127/503] Downloading CPRT...
[128/503] Downloading GLW...
[129/503] Downloading CPAY...
[130/503] Downloading CTVA...
[131/503] Downloading CSGP...
[132/503] Downloading COST...
[133/503] Downloading CRH...
[134/503] Downloading CRWD...
[135/503] Downloading CCI...
[136/503] Downloading CSX...
[137/503] Downloading CMI...
[138/503] Downloading CVS...
[139/503] Downloading DHR...
[140/503] Downloading DRI...
[141/503] Downloading DDOG...
[142/503] Downloading DVA...
[143/503] Downloading DECK...
[144/503] Downloading DE...
[145/503] Downloading DELL...
[146/503] Downloading DAL...
[147/503] Downloading DVN...
[148/503] Downloading DXCM...
[149/503] Downloading FANG...
[150/503] Downloading DLR...
[151/503] Downloading DG...
[152/503] Downloading DLTR...
[153/503] Downloading D...
[154/503] Downloading DPZ...
[155/503] Downloading DASH...
[156/503] Downloading DOV...
[157/503] Downloading DOW...
[158/503] Downloading DHI...
[159/503] Downloading DTE...
[160/503] Downloading DUK...
[161/503] Downloading DD...
[162/503] Downloading ETN...
[163/503] Downloading EBAY...
[164/503] Downloading ECHO...
[165/503] Downloading ECL...
[166/503] Downloading EIX...
[167/503] Downloading EW...
[168/503] Downloading EA...
[169/503] Downloading ELV...
[170/503] Downloading EME...
[171/503] Downloading EMR...
[172/503] Downloading ETR...
[173/503] Downloading EOG...
[174/503] Downloading EQT...
[175/503] Downloading EFX...
[176/503] Downloading EQIX...
[177/503] Downloading EQR...
[178/503] Downloading ERIE...
[179/503] Downloading ESS...
[180/503] Downloading EL...
[181/503] Downloading EG...
[182/503] Downloading EVRG...
[183/503] Downloading ES...
[184/503] Downloading EXC...
[185/503] Downloading EXE...
[186/503] Downloading EXPE...
[187/503] Downloading EXPD...
[188/503] Downloading EXR...
[189/503] Downloading XOM...
[190/503] Downloading FFIV...
[191/503] Downloading FDS...
[192/503] Downloading FICO...
[193/503] Downloading FAST...
[194/503] Downloading FRT...
[195/503] Downloading FDX...
[196/503] Downloading FDXF...

$FDXF: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1262322000, endDate = 1767243600")

1 Failed download:
['FDXF']: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1262322000, endDate = 1767243600")

  -> No data returned for FDXF
[197/503] Downloading FIS...
[198/503] Downloading FITB...
[199/503] Downloading FSLR...
[200/503] Downloading FE...
[201/503] Downloading FISV...
[202/503] Downloading FLEX...
[203/503] Downloading F...
[204/503] Downloading FTNT...
[205/503] Downloading FTV...
[206/503] Downloading FOXA...
[207/503] Downloading FOX...
[208/503] Downloading BEN...
[209/503] Downloading FCX...
[210/503] Downloading GRMN...
[211/503] Downloading IT...
[212/503] Downloading GE...
[213/503] Downloading GEHC...
[214/503] Downloading GEV...
[215/503] Downloading GEN...
[216/503] Downloading GNRC...
[217/503] Downloading GD...
[218/503] Downloading GIS...
[219/503] Downloading GM...
[220/503] Downloading GPC...
[221/503] Downloading GILD...
[222/503] Downloading GPN...
[223/503] Downloading GL...
[224/503] Downloading GDDY...
[225/503] Downloading GS...
[226/503] Downloading HAL...
[227/503] Downloading HIG...
[228/503] Downloading HAS...
[229/503] Downloading HCA...
[230/503] Downloading DOC...
[231/503] Downloading HSIC...
[232/503] Downloading HSY...
[233/503] Downloading HPE...
[234/503] Downloading HLT...
[235/503] Downloading HD...
[236/503] Downloading HONA...

$HONA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1262322000, endDate = 1767243600")

1 Failed download:
['HONA']: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1262322000, endDate = 1767243600")

  -> No data returned for HONA
[237/503] Downloading HON...
[238/503] Downloading HRL...
[239/503] Downloading HST...
[240/503] Downloading HWM...
[241/503] Downloading HPQ...
[242/503] Downloading HUBB...
[243/503] Downloading HUM...
[244/503] Downloading HBAN...
[245/503] Downloading HII...
[246/503] Downloading IBM...
[247/503] Downloading IEX...
[248/503] Downloading IDXX...
[249/503] Downloading ITW...
[250/503] Downloading INCY...
[251/503] Downloading IR...
[252/503] Downloading PODD...
[253/503] Downloading INTC...
[254/503] Downloading IBKR...
[255/503] Downloading ICE...
[256/503] Downloading IFF...
[257/503] Downloading IP...
[258/503] Downloading INTU...
[259/503] Downloading ISRG...
[260/503] Downloading IVZ...
[261/503] Downloading INVH...
[262/503] Downloading IQV...
[263/503] Downloading IRM...
[264/503] Downloading JBHT...
[265/503] Downloading JBL...
[266/503] Downloading JKHY...
[267/503] Downloading J...
[268/503] Downloading JNJ...
[269/503] Downloading JCI...
[270/503] Downloading JPM...
[271/503] Downloading KVUE...
[272/503] Downloading KDP...
[273/503] Downloading KEY...
[274/503] Downloading KEYS...
[275/503] Downloading KMB...
[276/503] Downloading KIM...
[277/503] Downloading KMI...
[278/503] Downloading KKR...
[279/503] Downloading KLAC...
[280/503] Downloading KHC...
[281/503] Downloading KR...
[282/503] Downloading LHX...
[283/503] Downloading LH...
[284/503] Downloading LRCX...
[285/503] Downloading LVS...
[286/503] Downloading LDOS...
[287/503] Downloading LEN...
[288/503] Downloading LII...
[289/503] Downloading LLY...
[290/503] Downloading LIN...
[291/503] Downloading LYV...
[292/503] Downloading LMT...
[293/503] Downloading L...
[294/503] Downloading LOW...
[295/503] Downloading LULU...
[296/503] Downloading LITE...
[297/503] Downloading LYB...
[298/503] Downloading MTB...
[299/503] Downloading MPC...
[300/503] Downloading MAR...
[301/503] Downloading MRSH...
[302/503] Downloading MLM...
[303/503] Downloading MRVL...
[304/503] Downloading MAS...
[305/503] Downloading MA...
[306/503] Downloading MKC...
[307/503] Downloading MCD...
[308/503] Downloading MCK...
[309/503] Downloading MDT...
[310/503] Downloading MRK...
[311/503] Downloading META...
[312/503] Downloading MET...
[313/503] Downloading MTD...
[314/503] Downloading MGM...
[315/503] Downloading MCHP...
[316/503] Downloading MU...
[317/503] Downloading MSFT...
[318/503] Downloading MAA...
[319/503] Downloading MRNA...
[320/503] Downloading TAP...
[321/503] Downloading MDLZ...
[322/503] Downloading MPWR...
[323/503] Downloading MNST...
[324/503] Downloading MCO...
[325/503] Downloading MS...
[326/503] Downloading MOS...
[327/503] Downloading MSI...
[328/503] Downloading MSCI...
[329/503] Downloading NDAQ...
[330/503] Downloading NTAP...
[331/503] Downloading NFLX...
[332/503] Downloading NEM...
[333/503] Downloading NWSA...
[334/503] Downloading NWS...
[335/503] Downloading NEE...
[336/503] Downloading NKE...
[337/503] Downloading NI...
[338/503] Downloading NDSN...
[339/503] Downloading NSC...
[340/503] Downloading NTRS...
[341/503] Downloading NOC...
[342/503] Downloading NCLH...
[343/503] Downloading NRG...
[344/503] Downloading NUE...
[345/503] Downloading NVDA...
[346/503] Downloading NVR...
[347/503] Downloading NXPI...
[348/503] Downloading ORLY...
[349/503] Downloading OXY...
[350/503] Downloading ODFL...
[351/503] Downloading OMC...
[352/503] Downloading ON...
[353/503] Downloading OKE...
[354/503] Downloading ORCL...
[355/503] Downloading OTIS...
[356/503] Downloading PCAR...
[357/503] Downloading PKG...
[358/503] Downloading PLTR...
[359/503] Downloading PANW...
[360/503] Downloading PSKY...
[361/503] Downloading PH...
[362/503] Downloading PAYX...
[363/503] Downloading PYPL...
[364/503] Downloading PNR...
[365/503] Downloading PEP...
[366/503] Downloading PFE...
[367/503] Downloading PCG...
[368/503] Downloading PM...
[369/503] Downloading PSX...
[370/503] Downloading PNW...
[371/503] Downloading PNC...
[372/503] Downloading PPG...
[373/503] Downloading PPL...
[374/503] Downloading PFG...
[375/503] Downloading PG...
[376/503] Downloading PGR...
[377/503] Downloading PLD...
[378/503] Downloading PRU...
[379/503] Downloading PEG...
[380/503] Downloading PTC...
[381/503] Downloading PSA...
[382/503] Downloading PHM...
[383/503] Downloading PWR...
[384/503] Downloading QCOM...
[385/503] Downloading DGX...
[386/503] Downloading Q...
[387/503] Downloading RL...
[388/503] Downloading RJF...
[389/503] Downloading RTX...
[390/503] Downloading O...
[391/503] Downloading REG...
[392/503] Downloading REGN...
[393/503] Downloading RF...
[394/503] Downloading RSG...
[395/503] Downloading RMD...
[396/503] Downloading RVTY...
[397/503] Downloading HOOD...
[398/503] Downloading ROK...
[399/503] Downloading ROL...
[400/503] Downloading ROP...
[401/503] Downloading ROST...
[402/503] Downloading RCL...
[403/503] Downloading SPGI...
[404/503] Downloading CRM...
[405/503] Downloading SNDK...
[406/503] Downloading SBAC...
[407/503] Downloading SLB...
[408/503] Downloading STX...
[409/503] Downloading SRE...
[410/503] Downloading NOW...
[411/503] Downloading SHW...
[412/503] Downloading SPG...
[413/503] Downloading SWKS...
[414/503] Downloading SJM...
[415/503] Downloading SW...
[416/503] Downloading SNA...
[417/503] Downloading SOLV...
[418/503] Downloading SO...
[419/503] Downloading LUV...
[420/503] Downloading SWK...
[421/503] Downloading SBUX...
[422/503] Downloading STT...
[423/503] Downloading STLD...
[424/503] Downloading STE...
[425/503] Downloading SYK...
[426/503] Downloading SMCI...
[427/503] Downloading SYF...
[428/503] Downloading SNPS...
[429/503] Downloading SYY...
[430/503] Downloading TMUS...
[431/503] Downloading TROW...
[432/503] Downloading TTWO...
[433/503] Downloading TPR...
[434/503] Downloading TRGP...
[435/503] Downloading TGT...
[436/503] Downloading TEL...
[437/503] Downloading TDY...
[438/503] Downloading TER...
[439/503] Downloading TSLA...
[440/503] Downloading TXN...
[441/503] Downloading TPL...
[442/503] Downloading TXT...
[443/503] Downloading TMO...
[444/503] Downloading TJX...
[445/503] Downloading TKO...
[446/503] Downloading TTD...
[447/503] Downloading TSCO...
[448/503] Downloading TT...
[449/503] Downloading TDG...
[450/503] Downloading TRV...
[451/503] Downloading TRMB...
[452/503] Downloading TFC...
[453/503] Downloading TYL...
[454/503] Downloading TSN...
[455/503] Downloading USB...
[456/503] Downloading UBER...
[457/503] Downloading UDR...
[458/503] Downloading ULTA...
[459/503] Downloading UNP...
[460/503] Downloading UAL...
[461/503] Downloading UPS...
[462/503] Downloading URI...
[463/503] Downloading UNH...
[464/503] Downloading UHS...
[465/503] Downloading VLO...
[466/503] Downloading VEEV...
[467/503] Downloading VTR...
[468/503] Downloading VLTO...
[469/503] Downloading VRSN...
[470/503] Downloading VRSK...
[471/503] Downloading VZ...
[472/503] Downloading VRTX...
[473/503] Downloading VRT...
[474/503] Downloading VTRS...
[475/503] Downloading VICI...
[476/503] Downloading V...
[477/503] Downloading VST...
[478/503] Downloading VMC...
[479/503] Downloading WRB...
[480/503] Downloading GWW...
[481/503] Downloading WAB...
[482/503] Downloading WMT...
[483/503] Downloading DIS...
[484/503] Downloading WBD...
[485/503] Downloading WM...
[486/503] Downloading WAT...
[487/503] Downloading WEC...
[488/503] Downloading WFC...
[489/503] Downloading WELL...
[490/503] Downloading WST...
[491/503] Downloading WDC...
[492/503] Downloading WY...
[493/503] Downloading WSM...
[494/503] Downloading WMB...
[495/503] Downloading WTW...
[496/503] Downloading WDAY...
[497/503] Downloading WYNN...
[498/503] Downloading XEL...
[499/503] Downloading XYL...
[500/503] Downloading YUM...
[501/503] Downloading ZBRA...
[502/503] Downloading ZBH...
[503/503] Downloading ZTS...

Download complete.
Saved prices to: /Users/neilyejjey/stock_signal_engine_v1/data/raw/prices.parquet
Saved failed tickers to: /Users/neilyejjey/stock_signal_engine_v1/data/raw/failed_tickers.csv
Price dataset shape: (1895356, 10)
Unique tickers downloaded: 501
Failed tickers: 2

,date,ticker,open,high,low,close,adj_close,volume,dividends,stock_splits
0,2010-01-04,A,22.453505,22.625179,22.267525,22.389128,19.772955,3815561,0.0,0.0
1,2010-01-05,A,22.324751,22.331903,22.002861,22.145924,19.558165,4186031,0.0,0.0
2,2010-01-06,A,22.067240,22.174536,22.002861,22.067240,19.488676,3243779,0.0,0.0
3,2010-01-07,A,22.017166,22.045780,21.816881,22.038628,19.463409,3095172,0.0,0.0
4,2010-01-08,A,21.917025,22.067240,21.745352,22.031473,19.457087,3733918,0.0,0.0

In [5]:
prices

,date,ticker,open,high,low,close,adj_close,volume,dividends,stock_splits
0,2010-01-04,A,22.453505,22.625179,22.267525,22.389128,19.772955,3815561,0.0,0.0
1,2010-01-05,A,22.324751,22.331903,22.002861,22.145924,19.558165,4186031,0.0,0.0
2,2010-01-06,A,22.067240,22.174536,22.002861,22.067240,19.488676,3243779,0.0,0.0
3,2010-01-07,A,22.017166,22.045780,21.816881,22.038628,19.463409,3095172,0.0,0.0
4,2010-01-08,A,21.917025,22.067240,21.745352,22.031473,19.457087,3733918,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
1895351,2025-12-24,ZTS,123.099998,125.690002,123.059998,125.489998,124.415276,2369000,0.0,0.0
1895352,2025-12-26,ZTS,125.160004,126.320000,124.800003,126.230003,125.148941,3226800,0.0,0.0
1895353,2025-12-29,ZTS,126.160004,126.849998,125.559998,125.980003,124.901085,4465600,0.0,0.0
1895354,2025-12-30,ZTS,125.550003,127.599998,125.449997,126.410004,125.327400,3230200,0.0,0.0
1895355,2025-12-31,ZTS,126.040001,126.839996,125.769997,125.820000,124.742447,2943300,0.0,0.0

In [6]:
# =========================================
# Download Benchmark / ETF Price Data
# =========================================
#
# These benchmarks can be used downstream for:
#   - forward excess return labels
#   - strategy comparison
#   - VOO/SPY benchmark analysis
#
# SPY has longer trading history.
# VOO is closer to the user's desired benchmark but starts in 2010.

BENCHMARK_TICKERS = ["SPY", "VOO"]
BENCHMARK_PRICE_FILE = RAW_DIR / "benchmark_prices.parquet"

benchmark_prices = []
failed_benchmarks = []

for ticker in BENCHMARK_TICKERS:
    try:
        print(f"Downloading benchmark {ticker}...")

        df = yf.download(
            ticker,
            start=START_DATE,
            end=END_DATE,
            auto_adjust=False,
            actions=True,
            progress=False,
            threads=False,
        )

        if df.empty:
            print(f"  -> No data returned for {ticker}")
            failed_benchmarks.append(ticker)
            continue

        df.columns = [
            col[0] if isinstance(col, tuple) else col
            for col in df.columns
        ]

        df = df.reset_index().rename(columns={
            "Date": "date",
            "Open": "open",
            "High": "high",
            "Low": "low",
            "Close": "close",
            "Adj Close": "adj_close",
            "Volume": "volume",
            "Dividends": "dividends",
            "Stock Splits": "stock_splits",
        })

        df["ticker"] = ticker

        expected_cols = [
            "date",
            "ticker",
            "open",
            "high",
            "low",
            "close",
            "adj_close",
            "volume",
            "dividends",
            "stock_splits",
        ]

        df = df[[col for col in expected_cols if col in df.columns]]

        if "dividends" not in df.columns:
            df["dividends"] = 0.0

        if "stock_splits" not in df.columns:
            df["stock_splits"] = 0.0

        df["date"] = pd.to_datetime(df["date"])
        df = df.sort_values(["ticker", "date"]).drop_duplicates(
            subset=["ticker", "date"]
        )

        benchmark_prices.append(df)

    except Exception as e:
        print(f"  -> Failed for benchmark {ticker}: {e}")
        failed_benchmarks.append(ticker)

if not benchmark_prices:
    raise ValueError("No benchmark price data was downloaded.")

benchmark_prices = pd.concat(benchmark_prices, ignore_index=True)
benchmark_prices = benchmark_prices.sort_values(["ticker", "date"]).reset_index(drop=True)

benchmark_prices.to_parquet(BENCHMARK_PRICE_FILE, index=False)

print("\nBenchmark download complete.")
print(f"Saved benchmark prices to: {BENCHMARK_PRICE_FILE}")
print("Shape:", benchmark_prices.shape)
print("Failed benchmarks:", failed_benchmarks)

benchmark_prices.head()

Downloading benchmark SPY...
Downloading benchmark VOO...

Benchmark download complete.
Saved benchmark prices to: /Users/neilyejjey/stock_signal_engine_v1/data/raw/benchmark_prices.parquet
Shape: (7876, 10)
Failed benchmarks: []

,date,ticker,open,high,low,close,adj_close,volume,dividends,stock_splits
0,2010-01-04,SPY,112.370003,113.389999,111.510002,113.330002,84.578468,118944600,0.0,0.0
1,2010-01-05,SPY,113.260002,113.680000,112.849998,113.629997,84.802353,111579900,0.0,0.0
2,2010-01-06,SPY,113.519997,113.989998,113.430000,113.709999,84.862068,116074400,0.0,0.0
3,2010-01-07,SPY,113.500000,114.330002,113.180000,114.190002,85.220284,131091100,0.0,0.0
4,2010-01-08,SPY,113.889999,114.620003,113.660004,114.570000,85.503876,126402800,0.0,0.0

In [9]:
# =========================================
# Download Current Snapshot Metadata
# =========================================
#
# WARNING:
# --------
# This is current metadata from yfinance.
# It must NOT be merged into historical training rows as if it were historical.
#
# Use cases:
#   - current deployment dashboard
#   - current market-cap sanity checks
#   - live scoring overlays
#   - portfolio explanation
#
# Not valid for:
#   - 2011-2022 historical model features

import numpy as np

CURRENT_SNAPSHOT_FILE = RAW_DIR / "current_ticker_snapshot.parquet"
CURRENT_SNAPSHOT_FAILED_FILE = RAW_DIR / "current_ticker_snapshot_failed.csv"

snapshot_rows = []
snapshot_failed = []

snapshot_fields = [
    "symbol",
    "shortName",
    "longName",
    "sector",
    "industry",
    "marketCap",
    "sharesOutstanding",
    "floatShares",
    "beta",
    "trailingPE",
    "forwardPE",
    "priceToBook",
    "enterpriseValue",
    "enterpriseToRevenue",
    "enterpriseToEbitda",
    "profitMargins",
    "operatingMargins",
    "grossMargins",
    "ebitdaMargins",
    "revenueGrowth",
    "earningsGrowth",
    "recommendationMean",
    "recommendationKey",
    "numberOfAnalystOpinions",
    "targetMeanPrice",
    "targetMedianPrice",
    "targetHighPrice",
    "targetLowPrice",
    "dividendYield",
    "payoutRatio",
    "currency",
    "exchange",
    "quoteType",
]

for i, ticker in enumerate(tickers, start=1):
    try:
        print(f"[{i}/{len(tickers)}] Fetching snapshot {ticker}...")

        info = yf.Ticker(ticker).get_info()

        if not info:
            snapshot_failed.append(ticker)
            continue

        row = {"ticker": ticker}

        for field in snapshot_fields:
            row[field] = info.get(field, np.nan)

        snapshot_rows.append(row)

        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        print(f"  -> Failed snapshot for {ticker}: {e}")
        snapshot_failed.append(ticker)

current_snapshot = pd.DataFrame(snapshot_rows)

# Standardize selected names
rename_map = {
    "marketCap": "current_market_cap",
    "sharesOutstanding": "current_shares_outstanding",
    "floatShares": "current_float_shares",
    "trailingPE": "current_trailing_pe",
    "forwardPE": "current_forward_pe",
    "priceToBook": "current_price_to_book",
    "enterpriseValue": "current_enterprise_value",
    "enterpriseToRevenue": "current_ev_to_revenue",
    "enterpriseToEbitda": "current_ev_to_ebitda",
    "profitMargins": "current_profit_margin",
    "operatingMargins": "current_operating_margin",
    "grossMargins": "current_gross_margin",
    "ebitdaMargins": "current_ebitda_margin",
    "revenueGrowth": "current_revenue_growth",
    "earningsGrowth": "current_earnings_growth",
    "recommendationMean": "current_recommendation_mean",
    "recommendationKey": "current_recommendation_key",
    "numberOfAnalystOpinions": "current_num_analyst_opinions",
    "targetMeanPrice": "current_target_mean_price",
    "targetMedianPrice": "current_target_median_price",
    "targetHighPrice": "current_target_high_price",
    "targetLowPrice": "current_target_low_price",
    "dividendYield": "current_dividend_yield",
    "payoutRatio": "current_payout_ratio",
}

current_snapshot = current_snapshot.rename(columns=rename_map)

current_snapshot["snapshot_date"] = pd.Timestamp.today().normalize()

current_snapshot.to_parquet(CURRENT_SNAPSHOT_FILE, index=False)

pd.DataFrame({"ticker": snapshot_failed}).to_csv(
    CURRENT_SNAPSHOT_FAILED_FILE,
    index=False,
)

print("\nCurrent snapshot download complete.")
print(f"Saved current snapshot to: {CURRENT_SNAPSHOT_FILE}")
print(f"Saved failed snapshot tickers to: {CURRENT_SNAPSHOT_FAILED_FILE}")
print("Shape:", current_snapshot.shape)
print("Failed:", len(snapshot_failed))

current_snapshot.head()

[1/503] Fetching snapshot MMM...
[2/503] Fetching snapshot AOS...
[3/503] Fetching snapshot ABT...
[4/503] Fetching snapshot ABBV...
[5/503] Fetching snapshot ACN...
[6/503] Fetching snapshot ADBE...
[7/503] Fetching snapshot AMD...
[8/503] Fetching snapshot AES...
[9/503] Fetching snapshot AFL...
[10/503] Fetching snapshot A...
[11/503] Fetching snapshot APD...
[12/503] Fetching snapshot ABNB...
[13/503] Fetching snapshot AKAM...
[14/503] Fetching snapshot ALB...
[15/503] Fetching snapshot ARE...
[16/503] Fetching snapshot ALGN...
[17/503] Fetching snapshot ALLE...
[18/503] Fetching snapshot LNT...
[19/503] Fetching snapshot ALL...
[20/503] Fetching snapshot GOOGL...
[21/503] Fetching snapshot GOOG...
[22/503] Fetching snapshot MO...
[23/503] Fetching snapshot AMZN...
[24/503] Fetching snapshot AMCR...
[25/503] Fetching snapshot AEE...
[26/503] Fetching snapshot AEP...
[27/503] Fetching snapshot AXP...
[28/503] Fetching snapshot AIG...
[29/503] Fetching snapshot AMT...
[30/503] Fetching snapshot AWK...
[31/503] Fetching snapshot AMP...
[32/503] Fetching snapshot AME...
[33/503] Fetching snapshot AMGN...
[34/503] Fetching snapshot APH...
[35/503] Fetching snapshot ADI...
[36/503] Fetching snapshot AON...
[37/503] Fetching snapshot APA...
[38/503] Fetching snapshot APO...
[39/503] Fetching snapshot AAPL...
[40/503] Fetching snapshot AMAT...
[41/503] Fetching snapshot APP...
[42/503] Fetching snapshot APTV...
[43/503] Fetching snapshot ACGL...
[44/503] Fetching snapshot ADM...
[45/503] Fetching snapshot ARES...
[46/503] Fetching snapshot ANET...
[47/503] Fetching snapshot AJG...
[48/503] Fetching snapshot AIZ...
[49/503] Fetching snapshot T...
[50/503] Fetching snapshot ATO...
[51/503] Fetching snapshot ADSK...
[52/503] Fetching snapshot ADP...
[53/503] Fetching snapshot AZO...
[54/503] Fetching snapshot AVB...
[55/503] Fetching snapshot AVY...
[56/503] Fetching snapshot AXON...
[57/503] Fetching snapshot BKR...
[58/503] Fetching snapshot BALL...
[59/503] Fetching snapshot BAC...
[60/503] Fetching snapshot BAX...
[61/503] Fetching snapshot BDX...
[62/503] Fetching snapshot BRK-B...
[63/503] Fetching snapshot BBY...
[64/503] Fetching snapshot TECH...
[65/503] Fetching snapshot BIIB...
[66/503] Fetching snapshot BLK...
[67/503] Fetching snapshot BX...
[68/503] Fetching snapshot XYZ...
[69/503] Fetching snapshot BNY...
[70/503] Fetching snapshot BA...
[71/503] Fetching snapshot BKNG...
[72/503] Fetching snapshot BSX...
[73/503] Fetching snapshot BMY...
[74/503] Fetching snapshot AVGO...
[75/503] Fetching snapshot BR...
[76/503] Fetching snapshot BRO...
[77/503] Fetching snapshot BF-B...
[78/503] Fetching snapshot BLDR...
[79/503] Fetching snapshot BG...
[80/503] Fetching snapshot BXP...
[81/503] Fetching snapshot CHRW...
[82/503] Fetching snapshot CDNS...
[83/503] Fetching snapshot CPT...
[84/503] Fetching snapshot COF...
[85/503] Fetching snapshot CAH...
[86/503] Fetching snapshot CCL...
[87/503] Fetching snapshot CARR...
[88/503] Fetching snapshot CVNA...
[89/503] Fetching snapshot CASY...
[90/503] Fetching snapshot CAT...
[91/503] Fetching snapshot CBOE...
[92/503] Fetching snapshot CBRE...
[93/503] Fetching snapshot CDW...
[94/503] Fetching snapshot COR...
[95/503] Fetching snapshot CNC...
[96/503] Fetching snapshot CNP...
[97/503] Fetching snapshot CF...
[98/503] Fetching snapshot CRL...
[99/503] Fetching snapshot SCHW...
[100/503] Fetching snapshot CHTR...
[101/503] Fetching snapshot CVX...
[102/503] Fetching snapshot CMG...
[103/503] Fetching snapshot CB...
[104/503] Fetching snapshot CHD...
[105/503] Fetching snapshot CIEN...
[106/503] Fetching snapshot CI...
[107/503] Fetching snapshot CINF...
[108/503] Fetching snapshot CTAS...
[109/503] Fetching snapshot CSCO...
[110/503] Fetching snapshot C...
[111/503] Fetching snapshot CFG...
[112/503] Fetching snapshot CLX...
[113/503] Fetching snapshot CME...
[114/503] Fetching snapshot CMS...
[115/503] Fetching snapshot KO...
[116/503] Fetching snapshot CTSH...
[117/503] Fetching snapshot COHR...
[118/503] Fetching snapshot COIN...
[119/503] Fetching snapshot CL...
[120/503] Fetching snapshot CMCSA...
[121/503] Fetching snapshot FIX...
[122/503] Fetching snapshot COP...
[123/503] Fetching snapshot ED...
[124/503] Fetching snapshot STZ...
[125/503] Fetching snapshot CEG...
[126/503] Fetching snapshot COO...
[127/503] Fetching snapshot CPRT...
[128/503] Fetching snapshot GLW...
[129/503] Fetching snapshot CPAY...
[130/503] Fetching snapshot CTVA...
[131/503] Fetching snapshot CSGP...
[132/503] Fetching snapshot COST...
[133/503] Fetching snapshot CRH...
[134/503] Fetching snapshot CRWD...
[135/503] Fetching snapshot CCI...
[136/503] Fetching snapshot CSX...
[137/503] Fetching snapshot CMI...
[138/503] Fetching snapshot CVS...
[139/503] Fetching snapshot DHR...
[140/503] Fetching snapshot DRI...
[141/503] Fetching snapshot DDOG...
[142/503] Fetching snapshot DVA...
[143/503] Fetching snapshot DECK...
[144/503] Fetching snapshot DE...
[145/503] Fetching snapshot DELL...
[146/503] Fetching snapshot DAL...
[147/503] Fetching snapshot DVN...
[148/503] Fetching snapshot DXCM...
[149/503] Fetching snapshot FANG...
[150/503] Fetching snapshot DLR...
[151/503] Fetching snapshot DG...
[152/503] Fetching snapshot DLTR...
[153/503] Fetching snapshot D...
[154/503] Fetching snapshot DPZ...
[155/503] Fetching snapshot DASH...
[156/503] Fetching snapshot DOV...
[157/503] Fetching snapshot DOW...
[158/503] Fetching snapshot DHI...
[159/503] Fetching snapshot DTE...
[160/503] Fetching snapshot DUK...
[161/503] Fetching snapshot DD...
[162/503] Fetching snapshot ETN...
[163/503] Fetching snapshot EBAY...
[164/503] Fetching snapshot ECHO...
[165/503] Fetching snapshot ECL...
[166/503] Fetching snapshot EIX...
[167/503] Fetching snapshot EW...
[168/503] Fetching snapshot EA...
[169/503] Fetching snapshot ELV...
[170/503] Fetching snapshot EME...
[171/503] Fetching snapshot EMR...
[172/503] Fetching snapshot ETR...
[173/503] Fetching snapshot EOG...
[174/503] Fetching snapshot EQT...
[175/503] Fetching snapshot EFX...
[176/503] Fetching snapshot EQIX...
[177/503] Fetching snapshot EQR...
[178/503] Fetching snapshot ERIE...
[179/503] Fetching snapshot ESS...
[180/503] Fetching snapshot EL...
[181/503] Fetching snapshot EG...
[182/503] Fetching snapshot EVRG...
[183/503] Fetching snapshot ES...
[184/503] Fetching snapshot EXC...
[185/503] Fetching snapshot EXE...
[186/503] Fetching snapshot EXPE...
[187/503] Fetching snapshot EXPD...
[188/503] Fetching snapshot EXR...
[189/503] Fetching snapshot XOM...
[190/503] Fetching snapshot FFIV...
[191/503] Fetching snapshot FDS...
[192/503] Fetching snapshot FICO...
[193/503] Fetching snapshot FAST...
[194/503] Fetching snapshot FRT...
[195/503] Fetching snapshot FDX...
[196/503] Fetching snapshot FDXF...
[197/503] Fetching snapshot FIS...
[198/503] Fetching snapshot FITB...
[199/503] Fetching snapshot FSLR...
[200/503] Fetching snapshot FE...
[201/503] Fetching snapshot FISV...
[202/503] Fetching snapshot FLEX...
[203/503] Fetching snapshot F...
[204/503] Fetching snapshot FTNT...
[205/503] Fetching snapshot FTV...
[206/503] Fetching snapshot FOXA...
[207/503] Fetching snapshot FOX...
[208/503] Fetching snapshot BEN...
[209/503] Fetching snapshot FCX...
[210/503] Fetching snapshot GRMN...
[211/503] Fetching snapshot IT...
[212/503] Fetching snapshot GE...
[213/503] Fetching snapshot GEHC...
[214/503] Fetching snapshot GEV...
[215/503] Fetching snapshot GEN...
[216/503] Fetching snapshot GNRC...
[217/503] Fetching snapshot GD...
[218/503] Fetching snapshot GIS...
[219/503] Fetching snapshot GM...
[220/503] Fetching snapshot GPC...
[221/503] Fetching snapshot GILD...
[222/503] Fetching snapshot GPN...
[223/503] Fetching snapshot GL...
[224/503] Fetching snapshot GDDY...
[225/503] Fetching snapshot GS...
[226/503] Fetching snapshot HAL...
[227/503] Fetching snapshot HIG...
[228/503] Fetching snapshot HAS...
[229/503] Fetching snapshot HCA...
[230/503] Fetching snapshot DOC...
[231/503] Fetching snapshot HSIC...
[232/503] Fetching snapshot HSY...
[233/503] Fetching snapshot HPE...
[234/503] Fetching snapshot HLT...
[235/503] Fetching snapshot HD...
[236/503] Fetching snapshot HONA...
[237/503] Fetching snapshot HON...
[238/503] Fetching snapshot HRL...
[239/503] Fetching snapshot HST...
[240/503] Fetching snapshot HWM...
[241/503] Fetching snapshot HPQ...
[242/503] Fetching snapshot HUBB...
[243/503] Fetching snapshot HUM...
[244/503] Fetching snapshot HBAN...
[245/503] Fetching snapshot HII...
[246/503] Fetching snapshot IBM...
[247/503] Fetching snapshot IEX...
[248/503] Fetching snapshot IDXX...
[249/503] Fetching snapshot ITW...
[250/503] Fetching snapshot INCY...
[251/503] Fetching snapshot IR...
[252/503] Fetching snapshot PODD...
[253/503] Fetching snapshot INTC...
[254/503] Fetching snapshot IBKR...
[255/503] Fetching snapshot ICE...
[256/503] Fetching snapshot IFF...
[257/503] Fetching snapshot IP...
[258/503] Fetching snapshot INTU...
[259/503] Fetching snapshot ISRG...
[260/503] Fetching snapshot IVZ...
[261/503] Fetching snapshot INVH...
[262/503] Fetching snapshot IQV...
[263/503] Fetching snapshot IRM...
[264/503] Fetching snapshot JBHT...
[265/503] Fetching snapshot JBL...
[266/503] Fetching snapshot JKHY...
[267/503] Fetching snapshot J...
[268/503] Fetching snapshot JNJ...
[269/503] Fetching snapshot JCI...
[270/503] Fetching snapshot JPM...
[271/503] Fetching snapshot KVUE...
[272/503] Fetching snapshot KDP...
[273/503] Fetching snapshot KEY...
[274/503] Fetching snapshot KEYS...
[275/503] Fetching snapshot KMB...
[276/503] Fetching snapshot KIM...
[277/503] Fetching snapshot KMI...
[278/503] Fetching snapshot KKR...
[279/503] Fetching snapshot KLAC...
[280/503] Fetching snapshot KHC...
[281/503] Fetching snapshot KR...
[282/503] Fetching snapshot LHX...
[283/503] Fetching snapshot LH...
[284/503] Fetching snapshot LRCX...
[285/503] Fetching snapshot LVS...
[286/503] Fetching snapshot LDOS...
[287/503] Fetching snapshot LEN...
[288/503] Fetching snapshot LII...
[289/503] Fetching snapshot LLY...
[290/503] Fetching snapshot LIN...
[291/503] Fetching snapshot LYV...
[292/503] Fetching snapshot LMT...
[293/503] Fetching snapshot L...
[294/503] Fetching snapshot LOW...
[295/503] Fetching snapshot LULU...
[296/503] Fetching snapshot LITE...
[297/503] Fetching snapshot LYB...
[298/503] Fetching snapshot MTB...
[299/503] Fetching snapshot MPC...
[300/503] Fetching snapshot MAR...
[301/503] Fetching snapshot MRSH...
[302/503] Fetching snapshot MLM...
[303/503] Fetching snapshot MRVL...
[304/503] Fetching snapshot MAS...
[305/503] Fetching snapshot MA...
[306/503] Fetching snapshot MKC...
[307/503] Fetching snapshot MCD...
[308/503] Fetching snapshot MCK...
[309/503] Fetching snapshot MDT...
[310/503] Fetching snapshot MRK...
[311/503] Fetching snapshot META...
[312/503] Fetching snapshot MET...
[313/503] Fetching snapshot MTD...
[314/503] Fetching snapshot MGM...
[315/503] Fetching snapshot MCHP...
[316/503] Fetching snapshot MU...
[317/503] Fetching snapshot MSFT...
[318/503] Fetching snapshot MAA...
[319/503] Fetching snapshot MRNA...
[320/503] Fetching snapshot TAP...
[321/503] Fetching snapshot MDLZ...
[322/503] Fetching snapshot MPWR...
[323/503] Fetching snapshot MNST...
[324/503] Fetching snapshot MCO...
[325/503] Fetching snapshot MS...
[326/503] Fetching snapshot MOS...
[327/503] Fetching snapshot MSI...
[328/503] Fetching snapshot MSCI...
[329/503] Fetching snapshot NDAQ...
[330/503] Fetching snapshot NTAP...
[331/503] Fetching snapshot NFLX...
[332/503] Fetching snapshot NEM...
[333/503] Fetching snapshot NWSA...
[334/503] Fetching snapshot NWS...
[335/503] Fetching snapshot NEE...
[336/503] Fetching snapshot NKE...
[337/503] Fetching snapshot NI...
[338/503] Fetching snapshot NDSN...
[339/503] Fetching snapshot NSC...
[340/503] Fetching snapshot NTRS...
[341/503] Fetching snapshot NOC...
[342/503] Fetching snapshot NCLH...
[343/503] Fetching snapshot NRG...
[344/503] Fetching snapshot NUE...
[345/503] Fetching snapshot NVDA...
[346/503] Fetching snapshot NVR...
[347/503] Fetching snapshot NXPI...
[348/503] Fetching snapshot ORLY...
[349/503] Fetching snapshot OXY...
[350/503] Fetching snapshot ODFL...
[351/503] Fetching snapshot OMC...
[352/503] Fetching snapshot ON...
[353/503] Fetching snapshot OKE...
[354/503] Fetching snapshot ORCL...
[355/503] Fetching snapshot OTIS...
[356/503] Fetching snapshot PCAR...
[357/503] Fetching snapshot PKG...
[358/503] Fetching snapshot PLTR...
[359/503] Fetching snapshot PANW...
[360/503] Fetching snapshot PSKY...
[361/503] Fetching snapshot PH...
[362/503] Fetching snapshot PAYX...
[363/503] Fetching snapshot PYPL...
[364/503] Fetching snapshot PNR...
[365/503] Fetching snapshot PEP...
[366/503] Fetching snapshot PFE...
[367/503] Fetching snapshot PCG...
[368/503] Fetching snapshot PM...
[369/503] Fetching snapshot PSX...
[370/503] Fetching snapshot PNW...
[371/503] Fetching snapshot PNC...
[372/503] Fetching snapshot PPG...
[373/503] Fetching snapshot PPL...
[374/503] Fetching snapshot PFG...
[375/503] Fetching snapshot PG...
[376/503] Fetching snapshot PGR...
[377/503] Fetching snapshot PLD...
[378/503] Fetching snapshot PRU...
[379/503] Fetching snapshot PEG...
[380/503] Fetching snapshot PTC...
[381/503] Fetching snapshot PSA...
[382/503] Fetching snapshot PHM...
[383/503] Fetching snapshot PWR...
[384/503] Fetching snapshot QCOM...
[385/503] Fetching snapshot DGX...
[386/503] Fetching snapshot Q...
[387/503] Fetching snapshot RL...
[388/503] Fetching snapshot RJF...
[389/503] Fetching snapshot RTX...
[390/503] Fetching snapshot O...
[391/503] Fetching snapshot REG...
[392/503] Fetching snapshot REGN...
[393/503] Fetching snapshot RF...
[394/503] Fetching snapshot RSG...
[395/503] Fetching snapshot RMD...
[396/503] Fetching snapshot RVTY...
[397/503] Fetching snapshot HOOD...
[398/503] Fetching snapshot ROK...
[399/503] Fetching snapshot ROL...
[400/503] Fetching snapshot ROP...
[401/503] Fetching snapshot ROST...
[402/503] Fetching snapshot RCL...
[403/503] Fetching snapshot SPGI...
[404/503] Fetching snapshot CRM...
[405/503] Fetching snapshot SNDK...
[406/503] Fetching snapshot SBAC...
[407/503] Fetching snapshot SLB...
[408/503] Fetching snapshot STX...
[409/503] Fetching snapshot SRE...
[410/503] Fetching snapshot NOW...
[411/503] Fetching snapshot SHW...
[412/503] Fetching snapshot SPG...
[413/503] Fetching snapshot SWKS...
[414/503] Fetching snapshot SJM...
[415/503] Fetching snapshot SW...
[416/503] Fetching snapshot SNA...
[417/503] Fetching snapshot SOLV...
[418/503] Fetching snapshot SO...
[419/503] Fetching snapshot LUV...
[420/503] Fetching snapshot SWK...
[421/503] Fetching snapshot SBUX...
[422/503] Fetching snapshot STT...
[423/503] Fetching snapshot STLD...
[424/503] Fetching snapshot STE...
[425/503] Fetching snapshot SYK...
[426/503] Fetching snapshot SMCI...
[427/503] Fetching snapshot SYF...
[428/503] Fetching snapshot SNPS...
[429/503] Fetching snapshot SYY...
[430/503] Fetching snapshot TMUS...
[431/503] Fetching snapshot TROW...
[432/503] Fetching snapshot TTWO...
[433/503] Fetching snapshot TPR...
[434/503] Fetching snapshot TRGP...
[435/503] Fetching snapshot TGT...
[436/503] Fetching snapshot TEL...
[437/503] Fetching snapshot TDY...
[438/503] Fetching snapshot TER...
[439/503] Fetching snapshot TSLA...
[440/503] Fetching snapshot TXN...
[441/503] Fetching snapshot TPL...
[442/503] Fetching snapshot TXT...
[443/503] Fetching snapshot TMO...
[444/503] Fetching snapshot TJX...
[445/503] Fetching snapshot TKO...
[446/503] Fetching snapshot TTD...
[447/503] Fetching snapshot TSCO...
[448/503] Fetching snapshot TT...
[449/503] Fetching snapshot TDG...
[450/503] Fetching snapshot TRV...
[451/503] Fetching snapshot TRMB...
[452/503] Fetching snapshot TFC...
[453/503] Fetching snapshot TYL...
[454/503] Fetching snapshot TSN...
[455/503] Fetching snapshot USB...
[456/503] Fetching snapshot UBER...
[457/503] Fetching snapshot UDR...
[458/503] Fetching snapshot ULTA...
[459/503] Fetching snapshot UNP...
[460/503] Fetching snapshot UAL...
[461/503] Fetching snapshot UPS...
[462/503] Fetching snapshot URI...
[463/503] Fetching snapshot UNH...
[464/503] Fetching snapshot UHS...
[465/503] Fetching snapshot VLO...
[466/503] Fetching snapshot VEEV...
[467/503] Fetching snapshot VTR...
[468/503] Fetching snapshot VLTO...
[469/503] Fetching snapshot VRSN...
[470/503] Fetching snapshot VRSK...
[471/503] Fetching snapshot VZ...
[472/503] Fetching snapshot VRTX...
[473/503] Fetching snapshot VRT...
[474/503] Fetching snapshot VTRS...
[475/503] Fetching snapshot VICI...
[476/503] Fetching snapshot V...
[477/503] Fetching snapshot VST...
[478/503] Fetching snapshot VMC...
[479/503] Fetching snapshot WRB...
[480/503] Fetching snapshot GWW...
[481/503] Fetching snapshot WAB...
[482/503] Fetching snapshot WMT...
[483/503] Fetching snapshot DIS...
[484/503] Fetching snapshot WBD...
[485/503] Fetching snapshot WM...
[486/503] Fetching snapshot WAT...
[487/503] Fetching snapshot WEC...
[488/503] Fetching snapshot WFC...
[489/503] Fetching snapshot WELL...
[490/503] Fetching snapshot WST...
[491/503] Fetching snapshot WDC...
[492/503] Fetching snapshot WY...
[493/503] Fetching snapshot WSM...
[494/503] Fetching snapshot WMB...
[495/503] Fetching snapshot WTW...
[496/503] Fetching snapshot WDAY...
[497/503] Fetching snapshot WYNN...
[498/503] Fetching snapshot XEL...
[499/503] Fetching snapshot XYL...
[500/503] Fetching snapshot YUM...
[501/503] Fetching snapshot ZBRA...
[502/503] Fetching snapshot ZBH...
[503/503] Fetching snapshot ZTS...

Current snapshot download complete.
Saved current snapshot to: /Users/neilyejjey/stock_signal_engine_v1/data/raw/current_ticker_snapshot.parquet
Saved failed snapshot tickers to: /Users/neilyejjey/stock_signal_engine_v1/data/raw/current_ticker_snapshot_failed.csv
Shape: (503, 35)
Failed: 0

,ticker,symbol,shortName,longName,sector,industry,current_market_cap,current_shares_outstanding,current_float_shares,beta,...,current_target_mean_price,current_target_median_price,current_target_high_price,current_target_low_price,current_dividend_yield,current_payout_ratio,currency,exchange,quoteType,snapshot_date
0,MMM,MMM,3M Company,3M Company,Industrials,Conglomerates,83429900288,521567261,5.206806e+08,1.095,...,170.78764,175.0,209.0,120.0,1.93,0.5723,USD,NYQ,EQUITY,2026-07-01
1,AOS,AOS,A.O. Smith Corporation,A. O. Smith Corporation,Industrials,Specialty Industrial Machinery,8564670464,111965465,1.097819e+08,1.175,...,70.45455,70.0,84.0,59.0,2.26,0.3733,USD,NYQ,EQUITY,2026-07-01
2,ABT,ABT,Abbott Laboratories,Abbott Laboratories,Healthcare,Medical Devices,160560332800,1741813154,1.731153e+09,0.620,...,116.54167,115.0,135.0,92.0,2.78,0.6723,USD,NYQ,EQUITY,2026-07-01
3,ABBV,ABBV,AbbVie Inc.,AbbVie Inc.,Healthcare,Drug Manufacturers - General,443571011584,1766792821,1.763648e+09,0.309,...,254.37930,258.0,328.0,200.0,2.75,3.2598,USD,NYQ,EQUITY,2026-07-01
4,ACN,ACN,Accenture plc,Accenture plc,Technology,Information Technology Services,80243965952,611942109,6.107855e+08,1.069,...,179.29080,179.0,275.0,130.0,5.24,0.5088,USD,NYQ,EQUITY,2026-07-01

In [10]:
# =========================================
# Data Inventory
# =========================================

data_inventory = []

for path in [
    TICKER_FILE,
    UNIVERSE_METADATA_FILE,
    PRICE_FILE,
    FAILED_FILE,
    BENCHMARK_PRICE_FILE,
    CURRENT_SNAPSHOT_FILE,
    CURRENT_SNAPSHOT_FAILED_FILE,
]:
    data_inventory.append({
        "file": str(path),
        "exists": path.exists(),
        "size_mb": path.stat().st_size / 1_000_000 if path.exists() else np.nan,
    })

data_inventory = pd.DataFrame(data_inventory)

data_inventory

                                                file  exists    size_mb
0  /Users/neilyejjey/stock_signal_engine_v1/data/...    True   0.002118
1  /Users/neilyejjey/stock_signal_engine_v1/data/...    True   0.053638
2  /Users/neilyejjey/stock_signal_engine_v1/data/...    True  49.197728
3  /Users/neilyejjey/stock_signal_engine_v1/data/...    True   0.000017
4  /Users/neilyejjey/stock_signal_engine_v1/data/...    True   0.372376
5  /Users/neilyejjey/stock_signal_engine_v1/data/...    True   0.125770
6  /Users/neilyejjey/stock_signal_engine_v1/data/...    True   0.000007